# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roman_numeral', models.CharField(max_length=250)),
                ('starting_num', models.IntegerField()),
            ],
        ),
    ]
