# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='times_converted',
            field=models.IntegerField(default=0),
        ),
    ]
