# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 18:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('page_date', models.DateField(default=datetime.datetime(2017, 1, 10, 18, 24, 59, 312930))),
                ('entry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tome_title', models.CharField(max_length=255)),
                ('number_of_pages', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WordSmith',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tome',
            name='word_smith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tome.WordSmith'),
        ),
        migrations.AddField(
            model_name='page',
            name='tome_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tome.Tome'),
        ),
    ]
